### Required libraries import

In [1]:
import numpy as np
import pandas as pd

### Question 1

In [2]:
a = np.array([1, 7, 3, 10, 14, 76, 4])
n = len(a)

for i in range(n):
    for j in range(i+1,n):
        if(a[i]+a[j])%7==0:
            print(i,j)

0 5
1 4
2 6
3 6


### Question 2

In [3]:
A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])
B = np.array([[5, 6, 7],[7, 8, 9],[1, 2, 3]])

A_inv = np.linalg.inv(A)
dot_product = np.dot(A_inv, B)
elementwise = A_inv * B
print("A inverse (A_inv):\n", A_inv)
print("\nDot product:\n", dot_product)
print("\nElement-wise multiplication:\n", elementwise)

A inverse (A_inv):
 [[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]

Dot product:
 [[ 0.86046512  1.1627907   1.46511628]
 [ 2.06976744  2.41860465  2.76744186]
 [-0.55813953 -0.68217054 -0.80620155]]

Element-wise multiplication:
 [[ 1.74418605 -0.8372093   0.65116279]
 [ 2.27906977  0.55813953 -0.41860465]
 [-0.27131783  0.21705426  0.11627907]]


### Question 3

In [4]:
data = np.array([[1, 2, 3, 4, 5], [1, 8, 2, 10, 11], [4, 5, 6, 7, 8],[7, 8, 9, 10, 11], [7, 18, 19, 10, 11]])
# (a) Creating DataFrame df
df = pd.DataFrame(data,columns=['A','B','C','D','E'])
# (b) Sort by column 'C' and create df2
df2 = df.sort_values(by='C')
# First 2 and last 2 rows of df2
print("First 2 rows:\n", df2.head(2))
print("\nLast 2 rows:\n", df2.tail(2))
# (c) df2 as NumPy array
print("\ndf2 as NumPy array:\n", df2.values)

First 2 rows:
    A  B  C   D   E
1  1  8  2  10  11
0  1  2  3   4   5

Last 2 rows:
    A   B   C   D   E
3  7   8   9  10  11
4  7  18  19  10  11

df2 as NumPy array:
 [[ 1  8  2 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]


### Question 4

In [5]:
A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])

eigenvalues, _ = np.linalg.eig(A)
spectral_radius = np.max(np.abs(eigenvalues))

print("Eigenvalues of A:\n", eigenvalues)
print("\nSpectral radius of A:\n", spectral_radius)

Eigenvalues of A:
 [10.5740355 +0.j          2.21298225+2.70229602j  2.21298225-2.70229602j]

Spectral radius of A:
 10.57403549813147


### Question 5

Part (a)

In [6]:
B = np.array([
    [5, 6, 7],
    [7, 8, 9],
    [1, 2, 3]
])

# Compute SVD
U, S, Vt = np.linalg.svd(B, full_matrices=False)

# Convert S to a diagonal matrix
Sigma = np.diag(S)

print("U matrix:\n", U)
print("\nSingular values S:\n", S)
print("\nSigma matrix:\n", Sigma)
print("\nVt matrix:\n", Vt)

U matrix:
 [[-0.58909693  0.10053691 -0.80178373]
 [-0.78215124 -0.32019549  0.53452248]
 [-0.20298829  0.94200169  0.26726124]]

Singular values S:
 [1.78028049e+01 1.02963004e+00 1.32011803e-15]

Sigma matrix:
 [[1.78028049e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02963004e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.32011803e-15]]

Vt matrix:
 [[-0.48439174 -0.57281806 -0.66124437]
 [-0.77375576 -0.07219979  0.62935619]
 [ 0.40824829 -0.81649658  0.40824829]]


Part (b)

In [7]:
# Reconstruct B using SVD components
B_recon = U @ Sigma @ Vt
# Check if reconstructed B is close to the original
is_close = np.allclose(B, B_recon, atol=1e-10)
print("Reconstruction accurate:", is_close)

Reconstruction accurate: True


Part (c)

In [8]:
# Spectral condition number (2-norm)
kappa_2 = S[0]/S[-1]  # Since S is sorted in descending order
print("Spectral (2-norm) condition number κ₂(B):", kappa_2)

Spectral (2-norm) condition number κ₂(B): 1.348576759642456e+16
